# Generated by Django 6.0.7 on 2026-07-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Optional. The device's normal IP address, just for reference.", null=True)),
                ('broadcast_address', models.GenericIPAddressField(default='255.255.255.255', help_text='Broadcast address to send the magic packet to, e.g. 255.255.255.255 or a subnet broadcast like 192.168.1.255.')),
                ('port', models.PositiveIntegerField(default=9, help_text='UDP port (7 or 9 are conventional).')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_woken_at', models.DateTimeField(blank=True, null=True)),
                ('wake_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
